---
# tasks file for ./roles/networks
  
- name: main / Install required network libraries
  yum:
    name: "{{ network_packages }}"
    
- name: main / Start NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: main / Add ethernet connection
  nmcli:
    type: ethernet
    conn_name: "{{ item.conn_name }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    state: present
  loop: "{{ network_ethernet }}"

- name: main / Load bonding module
  modprobe:
    name: bonding
    state: present

- name: main / Add bonding connection
  nmcli:
    type: bond
    conn_name: "{{ item.conn_name }}"
    mode: "balance-rr"
    state: present
  loop: "{{ network_bond }}"
  when: ansible_bond0 is not defined

- name: main / Modify bonding connection
  nmcli:
    type: bond
    conn_name: "{{ item.conn_name }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    state: present
  loop: "{{ network_bond }}"

- name: main / Add bonding slave connection
  nmcli:
    type: bond-slave
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    master: "{{ item.master }}"
    state: present
  loop: "{{ network_bond_slave }}"
