---
# tasks file for ./roles/nginx

- name: check_install / Allow ports for firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ nginx_firewalld_port }}"
