- name: Initialize OS setting for Linux Servers
  hosts: linux_servers
  become: true

  # environment:
  #   http_proxy: "http://proxy.example.local:8080"
  #   https_proxy: "http://proxy.example.local:8080"

  roles:
    - name: common/locale
      tags: "locale"
    - name: common/packages
      tags: "packages"
    - role: common/users
      tags: "users"
    - name: common/networks
      tags: "net"
    - name: common/resolver
      tags: "resolver"

  post_tasks:
    - name: Restart target nodes
      reboot:

    - name: Waiting connection
      wait_for_connection:
        delay: 5
        timeout: 60
